### ISSUE TITLE
Credit consumption when analysis settings are changed but results don't 

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#215] opened 2017-07-21 11:57 UTC
A frequent concern in @CartoDB/solutions, DO, like geocoding, consumes credits in certain situations where an analysis has already been ran and the settings altered but the results don't change, e.g.: In the new DO UI, when a new measurement is added, if the previous ones are already calculated they will be calculated again when analysis is applied.

Average user will expect their previous results to be cached in order to not consume more credits.

**Comment by AbelVM** [comment] 2017-07-21 12:07
Other example: 
* AoI (isochrones) of a dataset of malls
* The user add *ONE* new mall in the dataset ----> all of them are recalculated and the credits lost

**Comment by andrewbt** [comment] 2017-07-21 18:26
A good solution to this would be a "flatten layer" functionality. IE, have data, enrich from DO/isolines/geocoding, and _permanently save as new/the-same dataset_.

Currently every time you make a map from a non-georeferenced dataset, you have to apply the analysis in each map, eating credits each time. We need a UI-driven way to permanently persist geocodes...

**Comment by juanignaciosl** [comment] 2017-07-24 08:21
Yep, as you see, this is not directly related to DO (only) but to quotas and services cc @rochoa

**Comment by rochoa** [comment] 2017-07-24 08:55
> Average user will expect their previous results to be cached in order to not consume more credits.

And in most of the cases, they are. The problem is that the UI doesn't know that, so it will tell you it's going to consume credits.

**Comment by noguerol** [comment] 2017-07-24 10:56
But even when its cached, it does consume credits, right? So the solution is to implement on both sides.

**Comment by rochoa** [comment] 2017-07-24 12:04
If it's the same dataset and the very same analysis, it should not consume. Otherwise, it's a bug. Did you test it?

**Comment by noguerol** [comment] 2017-07-26 11:02
I've not being able to replicate it because of this https://github.com/CartoDB/bigmetadata/issues/224

Can anyone have a try to confirm what @rochoa says?

**Comment by ethervoid** [comment] 2017-07-31 16:15
Adding a new measurement means that is a new analysis because the parameters have changed so the analysis is executed again for all the measurements.

The DO analysis doesn't take into account incremental changes is an all-or-nothing operation so if any of the parameters or the input data change, the analysis is executed again.

Our analysis API works that way, you're not able to rerun the analysis because the result of the analysis is cached to avoid spending credits to get the same result.

The incremental way you are pointing is something we know but is related to how data services work instead of data observatory and the scope of that change is way out of this. It implies to change the internals of data services and the analysis API to make some analysis persistent as we had, for example, the geocoding in the editor where we have a column to know which rows were geocoded and which were not.

**Comment by noguerol** [comment] 2017-08-01 07:14
Currently a new measurement can't be added incrementally because of the previous cache table preventing the whole thing to run, so either we fix that and we don't consume credits or we run again the whole thing, right?

**Comment by rochoa** [comment] 2017-08-01 07:30
> Currently a new measurement can't be added incrementally because of the previous cache table preventing the whole thing to run

Can you explain that with more detail? I'm a bit lost about what you mean. Is this about #225? If so, can you add the STR there? So we can replicate the error and work on the solution.

**Comment by javitonino** [comment] 2017-08-02 09:22
I think I replicated #225 but that is only an UI glitch when using a cached analysis (https://github.com/CartoDB/bigmetadata/issues/225#issuecomment-319593606).

I have no problem adding a new measure to an existing analysis, which runs perfectly, and charges you for both measurement (as it is a new analysis, it cannot use the partial cache).

**Comment by noguerol** [comment] 2017-08-03 11:03
Exactly, we're not able to confirm your point @rochoa because of https://github.com/CartoDB/bigmetadata/issues/225

**Comment by jorgesancha** [comment] 2017-08-03 11:30
Closing - See #230

**Comment by noguerol** [comment] 2017-08-22 08:04
Based on the difficulties we have for doing this in time I reopen this for checking if my original hyphothesis:

> DO, like geocoding, consumes credits in certain situations where an analysis has already been ran and the settings altered but the results don't change,

and @rochoas one:

> If it's the same dataset and the very same analysis, it should not consume. Otherwise, it's a bug. Did you test it?

are true or not. @juanignaciosl to test it, because we no longer have a UI that reports credit consumption.

**Comment by rochoa** [comment] 2017-08-22 08:24
In order to validate this, can you provide the steps to reproduce the issue?

**Comment by noguerol** [comment] 2017-08-22 08:50
STR

1. Add one measurement, run the analysis
2. Add another measurement to the same node, **check credit notification**, run the analysis
3. Add a third measurement to the same node, **check credit notification**

The goal is to check the intended behavior: both credit notifications and final consumption don't taking into account the cached analysis of the same node.

**Comment by AbelVM** [comment] 2017-08-22 09:23
Alternative STR, that's valid for any analysis under quota management

1. Add one paid analysis to node X, which contains N features ----> N credits are used
2. Remove **ONE** feature of X node by filtering it with a widget
3. The analysis run again over N-1 features, while it already has those results... ----> N-1 credits are wasted

Same behavior when adding a new feature to the X node 

**IRL case:** A company manages a network of hundreds of malls and analyzes the AOI of each of them with isochrones like 15min, 30 min, 1h driving, and then, they use DO to get some measures about the people living within those AOI. If the add just one new mall, all is recalculated and credits are used again to calc the AOI and fetch the DO measures that they already had. This company wasted up to 5000 credits without noticing just playing with Builder, editing the location of just one of their malls.

**Comment by rochoa** [comment] 2017-08-22 14:17
As @ethervoid described in this very same issue a few weeks ago in https://github.com/CartoDB/bigmetadata/issues/215#issuecomment-319118877, neither of those use cases are supported by the current implementation of the analyses library.

With different inputs, parameters (as per https://github.com/CartoDB/bigmetadata/issues/215#issuecomment-323961842) or data (as per https://github.com/CartoDB/bigmetadata/issues/215#issuecomment-323970335), the resulting analysis is completely different and it has to be executed as a different/new one.

Although I totally understand and agree on what you, @noguerol and @AbelVM, are proposing, **this is not a bug, but how the current implementation works**.

This is another example of flexibility vs performance situation. Implementing analyses right now is quite straightforward: you have to write a query based on some parameters and any input data (another SQL query), it's quite flexible and works for almost any kind of arbitrary data as input. However, improving the performance, in terms of speed or cost, is not as easy because each analysis had to understand any small detail, for instance: what changed in the arbitrary input data? Is just a new row appended to the whole dataset? Did we alter a column that does not affect the current analysis? Or there were 5 rows modified within a 100k rows table that need to be recomputed because the geometry changed?

There are several alternatives to solve these situations: 
 - We can be way more clever about how each analysis handles duplication, reduces costs, and improves performance. This will introduce a huge complexity for each analysis. And we would have to reimplement all existing analysis to have all those cases. This also requires changes in the library we use to create/execute analysis.
 - If we want to reduce costs, we can also improve the way DS/DO work, delegating the duplication problem to it. So the DO/DS would have to handle the caching for improving performance and not incur extra costs. Bear in mind, caching is not easy and it's not free, it also introduces new costs.
 - Improve the analysis library to support incremental analysis. However, I don't find this interesting. If you think twice about the original problem, doing an analysis with two DO measures is the same as doing two DO analyses and later joining them. Or using several DO analyses behind the scenes instead of the multiple-measures DO analysis.

Also, for more of those advanced use cases, as the one described by @AbelVM, we might need a different approach: if we had an Analysis API you could execute your AOI+DO analyses over the new rows and later join to previous results in a different table.

**Comment by noguerol** [comment] 2017-08-22 15:56
Thank you for the details. I can't get the difference between (a) and (b), but I'm with you that (c) sounds the least convenient. I guess (b) is the one you recommend, but it sounds to me like more laborious than https://github.com/CartoDB/bigmetadata/issues/230 . If that is the case I recommend we go back to removing credits for DO and then we tackle this cached analysis credit thing in a different ticket, for the other DS.

**Comment by rochoa** [comment] 2017-08-22 17:02
The difference between (a) and (b) is that in (b) the DS/DO should handle all the logic about duplicated/already processed measurements/requests. Any of the solutions I proposed are a one-week thing, they require way more effort than that.

Yes, I agree the best current approach, and probably the only viable one in the short-term, is removing the checking of the [remainding] credits in DO.

**Comment by juanignaciosl** [comment] 2017-08-23 07:55
@noguerol @rochoa ok, we'll remove DO credit usage (which is handled at DS server). Maybe some frontend work will be needed to remove notifications, we'll manage it.

**Comment by noguerol** [comment] 2017-08-23 09:49
Just to be clear, this means we are not changing Data Services as in https://github.com/CartoDB/bigmetadata/issues/230 but only the requests from Data Observatory? If that's the case I guess we are neither going to flag the credits nor going to work on any limits for free accounts, right?

**Comment by juanignaciosl** [comment] 2017-08-23 10:25
AFAIK it's similar to #230, but with a simpler implementation approach. Instead of flagging, hardcoding DO requests at Data Services as "don't charge credits". DS is the piece that handles credit charges, it's not something that can be addressed at DO side. @ethervoid , am I right?

**Comment by ethervoid** [comment] 2017-08-23 10:34
We could make a workaround here but should be done in DS which, as @juanignaciosl said, is the service that manages the quota checks for DO.

In order to avoid FREE or personal accounts, we can check if the user has the quota set for their user/organization but not check if the user has surpassed the quota. 

This way we are able to filter the DO users based on the configuration and we could ignore how many credits they have used.

**Comment by noguerol** [comment] 2017-08-23 11:03
Sounds like a plan.

**Comment by ethervoid** [comment] 2017-08-23 12:01
Yep but as I said this is a workaround we should do the #230 approach whenever we can

**Comment by noguerol** [comment] 2017-08-23 12:36
Understood, but as soon as we can ship this thing, it works for me. Shall we open a new ticket for the workaround?

**Comment by juanignaciosl** [comment] 2017-08-23 13:31
I'd use this to keep context. The future approach is already there (#230).

**Comment by juanignaciosl** [comment] 2017-08-23 14:04
> I'd use this to keep context

**Comment by ethervoid** [comment] 2017-08-24 11:32
One thing we have to do is to deactivate the code that charges the users over-quota if they surpass their quota and have the `soft_limit` activated [here](https://github.com/CartoDB/cartodb-central/blob/master/app/models/user.rb#L1271) , [here](https://github.com/CartoDB/cartodb-central/blob/master/app/models/organization.rb#L656),

**Comment by ethervoid** [comment] 2017-08-24 11:38
This users are FREE with quota defined:

```
    username
-----------------
 academy45
 jennart3
 gartnertest6
 academy70
 saleiva-empty
 gartnertest5
 ultra-admin
 equifax
 gartnertest2
 santander-admin
 gartnertest1
 gartnertest4
 gartnertest3
 fnicollet
 academy41
 roofstock-admin
 magicbox
 gtodes
 orrh
 jjenkins
 rambo-test
 heyheyman
 academy63
 fractalia-admin
 coerh
 jgoi
 ethervoid
 sjha6
 emilio2
 cartoframes
 mikefab
 chenrick
 sightline
 cdbsol-admin
(34 rows)
```

and this are the account types which have at least 1 user with the DO quota defined:

```
 cartodb_production=# select account_type, count(*) from users where obs_general_quota > 0 group by account_type;
                  account_type                   | count
-------------------------------------------------+-------
 CARTO for Community - Annual                    |    33
 Academy-350                                     |     5
 Internal use engine - On-premises Lite - Annual |     1
 ENTERPRISE LUMP-SUM                             |    27
 INTERNAL                                        |     7
 ENTERPRISE SMALL LS AWS                         |    34
 BASIC NON-PROFIT                                |     1
 Academy                                         |     1
 Site License                                    |    11
 Internal use engine - Cloud - Annual            |   104
 MAGELLAN                                        |     1
 Cloud Engine & Enterprise Builder - Annual      |    13
 ENTERPRISE LUMP-SUM ACADEMIC                    |     1
 ire                                             |   210
 CARTO for the Classroom - Annual                |     5
 Enterprise Large Lumpsum AWS                    |     2
 FREE                                            |    34
 BASIC                                           |     1
 Enterprise Builder - On-premises - Annual       |     9
 Internal use engine - On-premises - Annual      |     1
 Enterprise Small + Lumpsum AWS                  |     8
 CARTO Trial Account                             |    34
 AMBASSADOR                                      |   264
 ENTERPRISE                                      |    18
 ORGANIZATION USER                               |   846
 OEM engine - Cloud - Annual                     |     4
 Enterprise Builder - Annual                     |    61
 CARTO for students - Annual                     |  3381
 PARTNER                                         |   175
(29 rows)
```

@noguerol any of this accounts shouldn't have DO with quota?

**Comment by ethervoid** [comment] 2017-08-24 14:17
We have disabled the Do quota check for users that have the quota or soft limit defined. Also, we're not going to charge them for over quota in case the user has `soft_limit` activated.

The remaining part is to review the users that shouldn't have the quota defined but they have it because they're going to be able to use DO.

**Comment by ethervoid** [comment] 2017-08-24 14:22
Another remaining task CartoDB/cartodb#12648

**Comment by noguerol** [comment] 2017-08-24 14:57
@ethervoid this means there is no limit for users without quota check?

Let me review the plans and I will give you an answer.

**Comment by ethervoid** [comment] 2017-08-24 15:00
@noguerol Yes, now all the users that have at least 1 credit of quota for DO or the soft limit activate are able to use the DO without restrictions but some few "FREE" users have quota for DO so we should investigate why are they having quota (I'm pretty sure most of them are users from CARTO ppl)

**Comment by noguerol** [comment] 2017-08-24 15:04
Yes. I'm having a look. 

Besides i'm using this private issue to clarify some of the questions in

a) Free and Personal users should not have access to DO
b) Grayed out analysis boxes is planned for the future but not in the scope now, so
c) Those users should not see the DO box, because returning nulls is not ok.

cc @javitonino @nobuti @xavijam

**Comment by noguerol** [comment] 2017-08-24 15:10
What if people start enriching 500k rows? I guess we'll have a performance issue, right?

**Comment by ethervoid** [comment] 2017-08-24 15:11
Yes, but we're able to limit the input of the analysis if we want through the analysis api. For example, we can reject DO analysis with input rows number greater than 10k

**Comment by jorgesancha** [comment] 2017-08-24 15:16
There are also timeout limits for any analysis, if I'm not mistaken

**Comment by ethervoid** [comment] 2017-08-24 15:23
I'm not sure of that, we go through the batch API with the analysis and we don't have DB timeout there. But @rochoa is more suitable for that confirmation

**Comment by noguerol** [comment] 2017-08-24 15:28
The goal is to be able to analyse as many rows as you can import, but credits were a natural barrier for misuse. Now that we don't have them it will be great to know what could happen with, lets say, a considerable ammount of our enterprise clients mistakenly running the analysis over half a million rows.

**Comment by rochoa** [comment] 2017-08-24 15:38
> There are also timeout limits for any analysis, if I'm not mistaken

Yes, that's correct.

> I'm not sure of that, we go through the batch API with the analysis and we don't have DB timeout there. But @rochoa is more suitable for that confirmation

We can set different timeouts per analysis type, see https://github.com/CartoDB/Windshaft-cartodb/blob/03dc2601048d248eed79912ba04c4d114790c6a3/config/environments/development.js.example#L242-L247.

So it's a matter to set the limit we want for the `data-observatory-multiple-measures` analysis.

**Comment by noguerol** [comment] 2017-08-24 15:45
But being the analysis processed linearly, to set a timeout is pretty similar that setting a row limit, right?

**Comment by javitonino** [comment] 2017-08-24 15:48
Nope, the time depends a lot on the type of geometry. For example: the analysis is much faster for points than for polygons.

**Comment by noguerol** [comment] 2017-08-25 10:55
Let's please continue the conversation here: https://github.com/CartoDB/cartodb-platform/issues/3547

**Comment by juanignaciosl** [comment] 2017-08-31 06:51
This will be closed when CartoDB/cartodb/issues/12648 is.

**Closed** 2017-08-31 07:07 UTC
Labels: Backend, enhancement
